### ISSUE TITLE
New semester started but viewer still shows nothing

### ISSUE THREAD

**Issue by william-buerk** [TheTripleV/uiuc-course-calendar#5]
Spring 2024 semester begins today, but the viewer is still not showing that I have any classes on my schedule (likely stuck on winter 2023-24 still).

In addition to updating to the new semester automatically, it might be nice to have the option to pick the semester you want to view manually in order to reduce the possibility of issues like this

**Comment by TheTripleV** [comment]
Feel free to open a PR similar to https://github.com/TheTripleV/uiuc-course-calendar/pull/4 updating the year and season and I'll approve.

Otherwise, I'll get to it in a few hours

**Comment by TheTripleV** [comment]
I merged it in. It should have updated now.

**Comment by TheTripleV** [comment]
#6
